const data = {
  "data": [
    {
      "name": "ABOVE THE CLOUDS (1)",
      "cards": [
        "Warden of Evos Isle",
        "Inniaz, the Gale Force",
        "Tide Skimmer",
        "Keen Glidemaster",
        "Roaming Ghostlight",
        "Wall of Runes",
        "Mistral Singer",
        "Unsubstantiate",
        "Rain of Revelation",
        "Rookie Mistake",
        "Lofty Denial",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Above the Clouds Island"
      ],
      "shortName": "ABOVE THE CLOUDS"
    },
    {
      "name": "ABOVE THE CLOUDS (2)",
      "cards": [
        "Serendib Efreet",
        "Inniaz, the Gale Force",
        "Tide Skimmer",
        "Keen Glidemaster",
        "Roaming Ghostlight",
        "Mistral Singer",
        "Wall of Runes",
        "Talrand's Invocation",
        "Rain of Revelation",
        "Unsubstantiate",
        "Frost Breath",
        "Lofty Denial",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Above the Clouds Island"
      ],
      "shortName": "ABOVE THE CLOUDS"
    },
    {
      "name": "ABOVE THE CLOUDS (3)",
      "cards": [
        "Windreader Sphinx",
        "Warden of Evos Isle",
        "Tide Skimmer",
        "Keen Glidemaster",
        "Roaming Ghostlight",
        "Wall of Runes",
        "Rain of Revelation",
        "Unsubstantiate",
        "Frost Breath",
        "Lofty Denial",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Above the Clouds Island"
      ],
      "shortName": "ABOVE THE CLOUDS"
    },
    {
      "name": "ABOVE THE CLOUDS (4)",
      "cards": [
        "Kira, Great Glass-Spinner",
        "Windstorm Drake",
        "Tide Skimmer",
        "Keen Glidemaster",
        "Roaming Ghostlight",
        "Mistral Singer",
        "Wall of Runes",
        "Rain of Revelation",
        "Unsubstantiate",
        "Rookie Mistake",
        "Lofty Denial",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Above the Clouds Island"
      ],
      "shortName": "ABOVE THE CLOUDS"
    },
    {
      "name": "ANGELS (1)",
      "cards": [
        "Emancipation Angel",
        "Serra Angel",
        "Angelic Page",
        "Voice of the Provinces",
        "Baneslayer Angel",
        "Anointed Chorister",
        "Celestial Enforcer",
        "Angelic Edict",
        "Angelic Ascension",
        "Feat of Resistance",
        "Guardian Idol",
        "Scroll of Avacyn",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Angels Plains"
      ],
      "shortName": "ANGELS"
    },
    {
      "name": "ANGELS (2)",
      "cards": [
        "Linvala, Keeper of Silence",
        "Angelic Arbiter",
        "Emancipation Angel",
        "Serra Angel",
        "Angelic Page",
        "Anointed Chorister",
        "Celestial Enforcer",
        "Angelic Edict",
        "Take Heart",
        "Angelic Ascension",
        "Guardian Idol",
        "Scroll of Avacyn",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Angels Plains"
      ],
      "shortName": "ANGELS"
    },
    {
      "name": "ARCHAEOLOGY (1)",
      "cards": [
        "Scholar of the Lost Trove",
        "Juggernaut",
        "Meteor Golem",
        "Ancestral Statue",
        "Archaeomender",
        "Archaeomender",
        "Erratic Visionary",
        "Lightning-Core Excavator",
        "Thirst for Knowledge",
        "Chromatic Sphere",
        "Hedron Archive",
        "Aether Spellbomb",
        "Buried Ruin",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Archaeology Island"
      ],
      "shortName": "ARCHAEOLOGY"
    },
    {
      "name": "ARCHAEOLOGY (2)",
      "cards": [
        "Scholar of the Lost Trove",
        "Juggernaut",
        "Meteor Golem",
        "Ancestral Statue",
        "Archaeomender",
        "Archaeomender",
        "Erratic Visionary",
        "Lightning-Core Excavator",
        "Thirst for Knowledge",
        "Dreamstone Hedron",
        "Aether Spellbomb",
        "Terrarion",
        "Buried Ruin",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Archaeology Island"
      ],
      "shortName": "ARCHAEOLOGY"
    },
    {
      "name": "ARCHAEOLOGY (3)",
      "cards": [
        "Sharding Sphinx",
        "Vedalken Archmage",
        "Juggernaut",
        "Meteor Golem",
        "Ancestral Statue",
        "Archaeomender",
        "Archaeomender",
        "Lightning-Core Excavator",
        "Prismite",
        "Thirst for Knowledge",
        "Hedron Archive",
        "Aether Spellbomb",
        "Buried Ruin",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Archaeology Island"
      ],
      "shortName": "ARCHAEOLOGY"
    },
    {
      "name": "ARCHAEOLOGY (4)",
      "cards": [
        "Scarecrone",
        "Juggernaut",
        "Meteor Golem",
        "Scuttlemutt",
        "Archaeomender",
        "Archaeomender",
        "Lightning-Core Excavator",
        "Jousting Dummy",
        "Signpost Scarecrow",
        "Thirst for Knowledge",
        "Aether Spellbomb",
        "Short Sword",
        "Buried Ruin",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Archaeology Island"
      ],
      "shortName": "ARCHAEOLOGY"
    },
    {
      "name": "BASRI",
      "cards": [
        "Basri Ket",
        "Concordia Pegasus",
        "Knight of the Tusk",
        "Basri's Lieutenant",
        "Tempered Veteran",
        "Siege Striker",
        "Staunch Shieldmate",
        "Basri's Acolyte",
        "Basri's Solidarity",
        "Legion's Judgment",
        "Feat of Resistance",
        "Faith's Fetters",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains"
      ],
      "shortName": "BASRI"
    },
    {
      "name": "CATS (1)",
      "cards": [
        "Keeper of Fables",
        "Initiate's Companion",
        "Pouncing Cheetah",
        "Feral Prowler",
        "Feline Sovereign",
        "Canopy Stalker",
        "Sabertooth Mauler",
        "Pridemalkin",
        "Enlarge",
        "Nature's Way",
        "Crushing Canopy",
        "Feral Invocation",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Cats Forest"
      ],
      "shortName": "CATS"
    },
    {
      "name": "CATS (2)",
      "cards": [
        "Keeper of Fables",
        "Initiate's Companion",
        "Penumbra Bobcat",
        "Feral Prowler",
        "Feline Sovereign",
        "Canopy Stalker",
        "Pridemalkin",
        "Enlarge",
        "Nature's Way",
        "Crushing Canopy",
        "Lurking Predators",
        "Feral Invocation",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Cats Forest"
      ],
      "shortName": "CATS"
    },
    {
      "name": "CHANDRA",
      "cards": [
        "Chandra, Heart of Fire",
        "Pyroclastic Elemental",
        "Young Pyromancer",
        "Fanatical Firebrand",
        "Chandra's Incinerator",
        "Chandra's Pyreling",
        "Chandra's Magmutt",
        "Chandra's Magmutt",
        "Flames of the Firebrand",
        "Pillar of Flame",
        "Hungry Flames",
        "Thrill of Possibility",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain"
      ],
      "shortName": "CHANDRA"
    },
    {
      "name": "DEVILISH (1)",
      "cards": [
        "Forge Devil",
        "Zurzoth, Chaos Rider",
        "Chained Brute",
        "Spiteful Prankster",
        "Torch Fiend",
        "Havoc Jester",
        "Hobblefiend",
        "Pitchburn Devils",
        "Traitorous Greed",
        "Dance with Devils",
        "Collateral Damage",
        "Heartfire",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Devilish Mountain"
      ],
      "shortName": "DEVILISH"
    },
    {
      "name": "DEVILISH (2)",
      "cards": [
        "Tibalt's Rager",
        "Zurzoth, Chaos Rider",
        "Chained Brute",
        "Spiteful Prankster",
        "Torch Fiend",
        "Torch Fiend",
        "Havoc Jester",
        "Hobblefiend",
        "Pitchburn Devils",
        "Traitorous Greed",
        "Collateral Damage",
        "Heartfire",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Devilish Mountain"
      ],
      "shortName": "DEVILISH"
    },
    {
      "name": "DEVILISH (3)",
      "cards": [
        "Chained Brute",
        "Spiteful Prankster",
        "Lightning-Core Excavator",
        "Torch Fiend",
        "Brash Taunter",
        "Havoc Jester",
        "Hobblefiend",
        "Pitchburn Devils",
        "Act of Treason",
        "Traitorous Greed",
        "Dance with Devils",
        "Collateral Damage",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Devilish Mountain"
      ],
      "shortName": "DEVILISH"
    },
    {
      "name": "DEVILISH (4)",
      "cards": [
        "Hellrider",
        "Sin Prodder",
        "Chained Brute",
        "Spiteful Prankster",
        "Lightning-Core Excavator",
        "Havoc Jester",
        "Hobblefiend",
        "Pitchburn Devils",
        "Act of Treason",
        "Traitorous Greed",
        "Collateral Damage",
        "Barrage of Expendables",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Devilish Mountain"
      ],
      "shortName": "DEVILISH"
    },
    {
      "name": "DINOSAURS (1)",
      "cards": [
        "Ghalta, Primal Hunger",
        "Drover of the Mighty",
        "Orazca Frillback",
        "Thrashing Brontodon",
        "Colossal Dreadmaw",
        "Ornery Dilophosaur",
        "Drowsing Tyrannodon",
        "Savage Stomp",
        "Commune with Dinosaurs",
        "Cultivate",
        "Crushing Canopy",
        "Setessan Training",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Dinosaurs Forest"
      ],
      "shortName": "DINOSAURS"
    },
    {
      "name": "DINOSAURS (2)",
      "cards": [
        "Selvala, Heart of the Wilds",
        "Drover of the Mighty",
        "Thundering Spineback",
        "Orazca Frillback",
        "Colossal Dreadmaw",
        "Ornery Dilophosaur",
        "Drowsing Tyrannodon",
        "Savage Stomp",
        "Commune with Dinosaurs",
        "Crushing Canopy",
        "New Horizons",
        "Garruk's Uprising",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Dinosaurs Forest"
      ],
      "shortName": "DINOSAURS"
    },
    {
      "name": "DINOSAURS (3)",
      "cards": [
        "Ghalta, Primal Hunger",
        "Drover of the Mighty",
        "Thundering Spineback",
        "Orazca Frillback",
        "Colossal Dreadmaw",
        "Ornery Dilophosaur",
        "Drowsing Tyrannodon",
        "Savage Stomp",
        "Commune with Dinosaurs",
        "Cultivate",
        "Crushing Canopy",
        "Titanic Growth",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Dinosaurs Forest"
      ],
      "shortName": "DINOSAURS"
    },
    {
      "name": "DINOSAURS (4)",
      "cards": [
        "Rampaging Brontodon",
        "Drover of the Mighty",
        "Orazca Frillback",
        "Thrashing Brontodon",
        "Colossal Dreadmaw",
        "Ornery Dilophosaur",
        "Drowsing Tyrannodon",
        "Savage Stomp",
        "Commune with Dinosaurs",
        "Primal Might",
        "New Horizons",
        "Garruk's Uprising",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Dinosaurs Forest"
      ],
      "shortName": "DINOSAURS"
    },
    {
      "name": "DISCARDING (1)",
      "cards": [
        "Fell Specter",
        "Tinybones, Trinket Thief",
        "Ravenous Chupacabra",
        "Entomber Exarch",
        "Burglar Rat",
        "Phyrexian Rager",
        "Slate Street Ruffian",
        "Wight of Precinct Six",
        "Wight of Precinct Six",
        "Assassin's Strike",
        "Mind Rot",
        "Death's Approach",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Discarding Swamp"
      ],
      "shortName": "DISCARDING"
    },
    {
      "name": "DISCARDING (2)",
      "cards": [
        "Liliana's Reaver",
        "Nyxathid",
        "Fell Specter",
        "Ravenous Chupacabra",
        "Entomber Exarch",
        "Burglar Rat",
        "Phyrexian Rager",
        "Slate Street Ruffian",
        "Wight of Precinct Six",
        "Wight of Precinct Six",
        "Assassin's Strike",
        "Death's Approach",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Discarding Swamp"
      ],
      "shortName": "DISCARDING"
    },
    {
      "name": "DOCTOR (1)",
      "cards": [
        "Brightmare",
        "Bulwark Giant",
        "Mesa Unicorn",
        "Speaker of the Heavens",
        "Anointed Chorister",
        "Basri's Acolyte",
        "Take Heart",
        "Swift Response",
        "Revitalize",
        "Faith's Fetters",
        "Griffin Aerie",
        "Light of Promise",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Doctor Plains"
      ],
      "shortName": "DOCTOR"
    },
    {
      "name": "DOCTOR (2)",
      "cards": [
        "Brightmare",
        "Stone Haven Pilgrim",
        "Angel of Mercy",
        "Speaker of the Heavens",
        "Anointed Chorister",
        "Basri's Acolyte",
        "Secure the Scene",
        "Revitalize",
        "Moment of Heroism",
        "Swift Response",
        "Griffin Aerie",
        "Light of Promise",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Doctor Plains"
      ],
      "shortName": "DOCTOR"
    },
    {
      "name": "DOCTOR (3)",
      "cards": [
        "Rhox Faithmender",
        "Brightmare",
        "Angel of Mercy",
        "Mesa Unicorn",
        "Anointed Chorister",
        "Basri's Acolyte",
        "Moment of Heroism",
        "Swift Response",
        "Revitalize",
        "Griffin Aerie",
        "Light of Promise",
        "Faith's Fetters",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Doctor Plains"
      ],
      "shortName": "DOCTOR"
    },
    {
      "name": "DOCTOR (4)",
      "cards": [
        "Alabaster Mage",
        "Brightmare",
        "Stone Haven Pilgrim",
        "Angel of Mercy",
        "Bulwark Giant",
        "Anointed Chorister",
        "Basri's Acolyte",
        "Swift Response",
        "Revitalize",
        "Cradle of Vitality",
        "Path of Bravery",
        "Griffin Aerie",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Doctor Plains"
      ],
      "shortName": "DOCTOR"
    },
    {
      "name": "DOGS (1)",
      "cards": [
        "Affa Guard Hound",
        "Supply Runners",
        "Cathar's Companion",
        "Trusty Retriever",
        "Pack Leader",
        "Selfless Savior",
        "Alpine Watchdog",
        "Rambunctious Mutt",
        "Release the Dogs",
        "Secure the Scene",
        "Feat of Resistance",
        "Pacifism",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Dogs Plains"
      ],
      "shortName": "DOGS"
    },
    {
      "name": "DOGS (2)",
      "cards": [
        "Isamaru, Hound of Konda",
        "Affa Guard Hound",
        "Supply Runners",
        "Cathar's Companion",
        "Trusty Retriever",
        "Pack Leader",
        "Alpine Watchdog",
        "Rambunctious Mutt",
        "Release the Dogs",
        "Secure the Scene",
        "Dauntless Onslaught",
        "Pacifism",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Dogs Plains"
      ],
      "shortName": "DOGS"
    },
    {
      "name": "DRAGONS (1)",
      "cards": [
        "Dragonloft Idol",
        "Rapacious Dragon",
        "Dragonspeaker Shaman",
        "Dragon Hatchling",
        "Lightning Shrieker",
        "Terror of the Peaks",
        "Hellkite Punisher",
        "Bathe in Dragonfire",
        "Dragon Fodder",
        "Draconic Roar",
        "Thrill of Possibility",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Dragons Mountain"
      ],
      "shortName": "DRAGONS"
    },
    {
      "name": "DRAGONS (2)",
      "cards": [
        "Lathliss, Dragon Queen",
        "Rapacious Dragon",
        "Dragonlord's Servant",
        "Furnace Whelp",
        "Dragon Hatchling",
        "Lightning Shrieker",
        "Gadrak, the Crown-Scourge",
        "Hellkite Punisher",
        "Dragon Fodder",
        "Draconic Roar",
        "Sarkhan's Rage",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Dragons Mountain"
      ],
      "shortName": "DRAGONS"
    },
    {
      "name": "ELVES (1)",
      "cards": [
        "Craterhoof Behemoth",
        "Elvish Archdruid",
        "Dwynen's Elite",
        "Ghirapur Guide",
        "Silhana Wayfinder",
        "Wildheart Invoker",
        "Skyway Sniper",
        "Llanowar Visionary",
        "Hunter's Edge",
        "Crushing Canopy",
        "Titanic Growth",
        "Presence of Gond",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Elves Forest"
      ],
      "shortName": "ELVES"
    },
    {
      "name": "ELVES (2)",
      "cards": [
        "Dwynen's Elite",
        "Allosaurus Shepherd",
        "Silhana Wayfinder",
        "Wren's Run Vanquisher",
        "Leaf Gilder",
        "Wildheart Invoker",
        "Skyway Sniper",
        "Llanowar Visionary",
        "Hunter's Edge",
        "Crushing Canopy",
        "Titanic Growth",
        "Presence of Gond",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Elves Forest"
      ],
      "shortName": "ELVES"
    },
    {
      "name": "ENCHANTED (1)",
      "cards": [
        "Kor Spiritdancer",
        "Blessed Spirits",
        "Stone Haven Pilgrim",
        "Trusty Retriever",
        "Knight of the Tusk",
        "Anointed Chorister",
        "Face of Divinity",
        "Knightly Valor",
        "Forced Worship",
        "Indomitable Will",
        "Faith's Fetters",
        "Dub",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Enchanted Plains"
      ],
      "shortName": "ENCHANTED"
    },
    {
      "name": "ENCHANTED (2)",
      "cards": [
        "Ajani's Chosen",
        "Blessed Spirits",
        "Stone Haven Pilgrim",
        "Bulwark Giant",
        "Trusty Retriever",
        "Staunch Shieldmate",
        "Celestial Mantle",
        "Face of Divinity",
        "Knightly Valor",
        "Forced Worship",
        "Indomitable Will",
        "Faith's Fetters",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Enchanted Plains"
      ],
      "shortName": "ENCHANTED"
    },
    {
      "name": "FEATHERED FRIENDS (1)",
      "cards": [
        "Healer's Hawk",
        "Steel-Plume Marshal",
        "Aven Gagglemaster",
        "Falconer Adept",
        "Concordia Pegasus",
        "Warded Battlements",
        "Gale Swooper",
        "Celestial Enforcer",
        "Aerial Assault",
        "Dauntless Onslaught",
        "Moment of Heroism",
        "Sky Tether",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Feathered Friends Plains"
      ],
      "shortName": "FEATHERED FRIENDS"
    },
    {
      "name": "FEATHERED FRIENDS (2)",
      "cards": [
        "Concordia Pegasus",
        "Steel-Plume Marshal",
        "Healer's Hawk",
        "Aven Gagglemaster",
        "Falconer Adept",
        "Warded Battlements",
        "Gale Swooper",
        "Celestial Enforcer",
        "Tandem Tactics",
        "Angelic Ascension",
        "Swift Response",
        "Sky Tether",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Feathered Friends Plains"
      ],
      "shortName": "FEATHERED FRIENDS"
    },
    {
      "name": "FEATHERED FRIENDS (3)",
      "cards": [
        "Angel of the Dire Hour",
        "Healer's Hawk",
        "Aven Gagglemaster",
        "Falconer Adept",
        "Concordia Pegasus",
        "Warded Battlements",
        "Gale Swooper",
        "Celestial Enforcer",
        "Dauntless Onslaught",
        "Take Heart",
        "Swift Response",
        "Sky Tether",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Feathered Friends Plains"
      ],
      "shortName": "FEATHERED FRIENDS"
    },
    {
      "name": "FEATHERED FRIENDS (4)",
      "cards": [
        "Archon of Justice",
        "Archon of Redemption",
        "Healer's Hawk",
        "Falconer Adept",
        "Concordia Pegasus",
        "Warded Battlements",
        "Gale Swooper",
        "Celestial Enforcer",
        "Aerial Assault",
        "Aegis of the Heavens",
        "Dauntless Onslaught",
        "Sky Tether",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Feathered Friends Plains"
      ],
      "shortName": "FEATHERED FRIENDS"
    },
    {
      "name": "GARRUK",
      "cards": [
        "Garruk, Unleashed",
        "Affectionate Indrik",
        "Brushstrider",
        "Rumbling Baloth",
        "Orazca Frillback",
        "Garruk's Harbinger",
        "Garruk's Gorehorn",
        "Drowsing Tyrannodon",
        "Hunter's Edge",
        "Hunter's Insight",
        "Ranger's Guile",
        "Garruk's Uprising",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest"
      ],
      "shortName": "GARRUK"
    },
    {
      "name": "GOBLINS (1)",
      "cards": [
        "Beetleback Chief",
        "Muxus, Goblin Grandee",
        "Goblin Commando",
        "Volley Veteran",
        "Boggart Brute",
        "Goblin Instigator",
        "Goblin Shortcutter",
        "Ornery Goblin",
        "Goblin Arsonist",
        "Outnumber",
        "Shock",
        "Makeshift Munitions",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Goblins Mountain"
      ],
      "shortName": "GOBLINS"
    },
    {
      "name": "GOBLINS (2)",
      "cards": [
        "Goblin Instigator",
        "Muxus, Goblin Grandee",
        "Beetleback Chief",
        "Goblin Commando",
        "Boggart Brute",
        "Goblin Shortcutter",
        "Ornery Goblin",
        "Battle-Rattle Shaman",
        "Goblin Arsonist",
        "Outnumber",
        "Burn Bright",
        "Makeshift Munitions",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Goblins Mountain"
      ],
      "shortName": "GOBLINS"
    },
    {
      "name": "GOBLINS (3)",
      "cards": [
        "Goblin Chieftain",
        "Goblin Goon",
        "Beetleback Chief",
        "Goblin Commando",
        "Volley Veteran",
        "Boggart Brute",
        "Goblin Instigator",
        "Goblin Shortcutter",
        "Ornery Goblin",
        "Goblin Arsonist",
        "Shock",
        "Makeshift Munitions",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Goblins Mountain"
      ],
      "shortName": "GOBLINS"
    },
    {
      "name": "GOBLINS (4)",
      "cards": [
        "Krenko, Mob Boss",
        "Goblin Commando",
        "Boggart Brute",
        "Goblin Instigator",
        "Goblin Shortcutter",
        "Ornery Goblin",
        "Goblin Arsonist",
        "Goblin Lore",
        "Goblin Rally",
        "Outnumber",
        "Burn Bright",
        "Makeshift Munitions",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Goblins Mountain"
      ],
      "shortName": "GOBLINS"
    },
    {
      "name": "HEAVILY ARMORED (1)",
      "cards": [
        "Patron of the Valiant",
        "Bulwark Giant",
        "Trusty Retriever",
        "Lightwalker",
        "Tempered Veteran",
        "Siege Striker",
        "Makeshift Battalion",
        "Basri's Acolyte",
        "Basri's Solidarity",
        "Secure the Scene",
        "Feat of Resistance",
        "Cathars' Crusade",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Heavily Armored Plains"
      ],
      "shortName": "HEAVILY ARMORED"
    },
    {
      "name": "HEAVILY ARMORED (2)",
      "cards": [
        "Patron of the Valiant",
        "Bulwark Giant",
        "Trusty Retriever",
        "Lightwalker",
        "Tempered Veteran",
        "Siege Striker",
        "Makeshift Battalion",
        "Basri's Acolyte",
        "Gird for Battle",
        "Secure the Scene",
        "Battlefield Promotion",
        "Cathars' Crusade",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Heavily Armored Plains"
      ],
      "shortName": "HEAVILY ARMORED"
    },
    {
      "name": "HEAVILY ARMORED (3)",
      "cards": [
        "Mikaeus, the Lunarch",
        "Patron of the Valiant",
        "Supply Runners",
        "Bulwark Giant",
        "Trusty Retriever",
        "Lightwalker",
        "Tempered Veteran",
        "Makeshift Battalion",
        "Basri's Acolyte",
        "Basri's Solidarity",
        "Battlefield Promotion",
        "Divine Arrow",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Heavily Armored Plains"
      ],
      "shortName": "HEAVILY ARMORED"
    },
    {
      "name": "HEAVILY ARMORED (4)",
      "cards": [
        "High Sentinels of Arashin",
        "Supply Runners",
        "Bulwark Giant",
        "Trusty Retriever",
        "Lightwalker",
        "Tempered Veteran",
        "Siege Striker",
        "Makeshift Battalion",
        "Basri's Acolyte",
        "Long Road Home",
        "Swift Response",
        "Duelist's Heritage",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Heavily Armored Plains"
      ],
      "shortName": "HEAVILY ARMORED"
    },
    {
      "name": "LANDS (1)",
      "cards": [
        "Ulvenwald Hydra",
        "Awakener Druid",
        "Feral Hydra",
        "Fa'adiyah Seer",
        "Fertilid",
        "Sylvan Ranger",
        "Wildheart Invoker",
        "Cultivate",
        "Crushing Canopy",
        "Elemental Uprising",
        "Zendikar's Roil",
        "Vastwood Zendikon",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Lands Forest"
      ],
      "shortName": "LANDS"
    },
    {
      "name": "LANDS (2)",
      "cards": [
        "Oracle of Mul Daya",
        "Awakener Druid",
        "Feral Hydra",
        "Woodborn Behemoth",
        "Fa'adiyah Seer",
        "Fertilid",
        "Sporemound",
        "Sylvan Ranger",
        "Wildheart Invoker",
        "Cultivate",
        "Crushing Canopy",
        "Elemental Uprising",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Lands Forest"
      ],
      "shortName": "LANDS"
    },
    {
      "name": "LEGION (1)",
      "cards": [
        "Knight of the Tusk",
        "Selfless Savior",
        "Falconer Adept",
        "Valorous Steed",
        "Daybreak Charger",
        "Makeshift Battalion",
        "Basri's Solidarity",
        "Legion's Judgment",
        "Path to Exile",
        "Inspired Charge",
        "Raise the Alarm",
        "Blessed Sanctuary",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Legion Plains"
      ],
      "shortName": "LEGION"
    },
    {
      "name": "LEGION (2)",
      "cards": [
        "Inspiring Captain",
        "Siege Striker",
        "Valorous Steed",
        "Daybreak Charger",
        "Makeshift Battalion",
        "Staunch Shieldmate",
        "Release the Dogs",
        "Basri's Solidarity",
        "Legion's Judgment",
        "Raise the Alarm",
        "Glorious Anthem",
        "Faith's Fetters",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Legion Plains"
      ],
      "shortName": "LEGION"
    },
    {
      "name": "LEGION (3)",
      "cards": [
        "Siege Striker",
        "Valorous Steed",
        "Daybreak Charger",
        "Makeshift Battalion",
        "Staunch Shieldmate",
        "Legion's Judgment",
        "Release the Dogs",
        "Basri's Solidarity",
        "Fortify",
        "Raise the Alarm",
        "Glorious Anthem",
        "Faith's Fetters",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Legion Plains"
      ],
      "shortName": "LEGION"
    },
    {
      "name": "LEGION (4)",
      "cards": [
        "Lena, Selfless Champion",
        "Mentor of the Meek",
        "Siege Striker",
        "Selfless Savior",
        "Valorous Steed",
        "Daybreak Charger",
        "Makeshift Battalion",
        "Basri's Solidarity",
        "Legion's Judgment",
        "Fortify",
        "Raise the Alarm",
        "Faith's Fetters",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Legion Plains"
      ],
      "shortName": "LEGION"
    },
    {
      "name": "LIGHTNING (1)",
      "cards": [
        "Weaver of Lightning",
        "Lightning Phoenix",
        "Living Lightning",
        "Lightning Visionary",
        "Lightning Visionary",
        "Lightning Elemental",
        "Lightning Shrieker",
        "Lightning-Core Excavator",
        "Homing Lightning",
        "Lightning Axe",
        "Lightning Bolt",
        "Lightning Diadem",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Lightning Mountain"
      ],
      "shortName": "LIGHTNING"
    },
    {
      "name": "LIGHTNING (2)",
      "cards": [
        "Ball Lightning",
        "Lightning Phoenix",
        "Living Lightning",
        "Weaver of Lightning",
        "Lightning Visionary",
        "Lightning Visionary",
        "Lightning Elemental",
        "Lightning-Core Excavator",
        "Chain Lightning",
        "Lightning Axe",
        "Riddle of Lightning",
        "Lightning Diadem",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Lightning Mountain"
      ],
      "shortName": "LIGHTNING"
    },
    {
      "name": "LILIANA",
      "cards": [
        "Liliana, Waker of the Dead",
        "Liliana's Elite",
        "Blighted Bat",
        "Ghoulraiser",
        "Wailing Ghoul",
        "Liliana's Standard Bearer",
        "Goremand",
        "Liliana's Devotee",
        "Liliana's Steward",
        "Settle the Score",
        "Cemetery Recruitment",
        "Rise Again",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp"
      ],
      "shortName": "LILIANA"
    },
    {
      "name": "MILLING",
      "cards": [
        "Bruvac the Grandiloquent",
        "Belltower Sphinx",
        "Reckless Scholar",
        "Wall of Lost Thoughts",
        "Selhoff Occultist",
        "Vedalken Entrancer",
        "Towering-Wave Mystic",
        "Sweep Away",
        "Thought Collapse",
        "Thought Scour",
        "Teferi's Tutelage",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Milling Island"
      ],
      "shortName": "MILLING"
    },
    {
      "name": "MINIONS (1)",
      "cards": [
        "Ghoulcaller's Accomplice",
        "Kels, Fight Fixer",
        "Bone Picker",
        "Dutiful Attendant",
        "Nocturnal Feeder",
        "Shambling Goblin",
        "Goremand",
        "Crypt Lurker",
        "Innocent Blood",
        "Eliminate",
        "Village Rites",
        "Witch's Cauldron",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Minions Swamp"
      ],
      "shortName": "MINIONS"
    },
    {
      "name": "MINIONS (2)",
      "cards": [
        "Eternal Taskmaster",
        "Kels, Fight Fixer",
        "Drainpipe Vermin",
        "Dutiful Attendant",
        "Ghoulcaller's Accomplice",
        "Nocturnal Feeder",
        "Goremand",
        "Crypt Lurker",
        "Bone Splinters",
        "Eliminate",
        "Village Rites",
        "Witch's Cauldron",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Minions Swamp"
      ],
      "shortName": "MINIONS"
    },
    {
      "name": "MINIONS (3)",
      "cards": [
        "Dutiful Attendant",
        "Drainpipe Vermin",
        "Ghoulcaller's Accomplice",
        "Nocturnal Feeder",
        "Goremand",
        "Liliana's Devotee",
        "Fetid Imp",
        "Crypt Lurker",
        "Launch Party",
        "Eliminate",
        "Village Rites",
        "Witch's Cauldron",
        "Phyrexian Tower",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Minions Swamp"
      ],
      "shortName": "MINIONS"
    },
    {
      "name": "MINIONS (4)",
      "cards": [
        "Ghoulcaller Gisa",
        "Dutiful Attendant",
        "Ghoulcaller's Accomplice",
        "Nocturnal Feeder",
        "Shambling Goblin",
        "Goremand",
        "Liliana's Devotee",
        "Fetid Imp",
        "Innocent Blood",
        "Eliminate",
        "Village Rites",
        "Witch's Cauldron",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Minions Swamp"
      ],
      "shortName": "MINIONS"
    },
    {
      "name": "MINOTAURS (1)",
      "cards": [
        "Bloodrage Brawler",
        "Sethron, Hurloon General",
        "Warfire Javelineer",
        "Borderland Minotaur",
        "Lightning Visionary",
        "Minotaur Skullcleaver",
        "Minotaur Sureshot",
        "Flurry of Horns",
        "Mugging",
        "Soul Sear",
        "Sure Strike",
        "Herald's Horn",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Minotaurs Mountain"
      ],
      "shortName": "MINOTAURS"
    },
    {
      "name": "MINOTAURS (2)",
      "cards": [
        "Rageblood Shaman",
        "Sethron, Hurloon General",
        "Bloodrage Brawler",
        "Borderland Minotaur",
        "Lightning Visionary",
        "Minotaur Skullcleaver",
        "Minotaur Sureshot",
        "Flurry of Horns",
        "Traitorous Greed",
        "Unleash Fury",
        "Soul Sear",
        "Sure Strike",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Minotaurs Mountain"
      ],
      "shortName": "MINOTAURS"
    },
    {
      "name": "PHYREXIAN",
      "cards": [
        "Sheoldred, Whispering One",
        "Entomber Exarch",
        "Phyrexian Gargantua",
        "Myr Sire",
        "Perilous Myr",
        "Phyrexian Broodlings",
        "Phyrexian Debaser",
        "Phyrexian Rager",
        "Douse in Gloom",
        "Malefic Scythe",
        "Phyrexian Reclamation",
        "Parasitic Implant",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Phyrexian Swamp"
      ],
      "shortName": "PHYREXIAN"
    },
    {
      "name": "PIRATES (1)",
      "cards": [
        "Rishadan Airship",
        "Corsair Captain",
        "Departed Deckhand",
        "Spectral Sailor",
        "Kitesail Corsair",
        "Prosperous Pirates",
        "Sailor of Means",
        "Chart a Course",
        "Voyage's End",
        "Pirate's Cutlass",
        "Coastal Piracy",
        "Waterknot",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Pirates Island"
      ],
      "shortName": "PIRATES"
    },
    {
      "name": "PIRATES (2)",
      "cards": [
        "Departed Deckhand",
        "Corsair Captain",
        "Spectral Sailor",
        "Kitesail Corsair",
        "Prosperous Pirates",
        "Rishadan Airship",
        "Sailor of Means",
        "Chart a Course",
        "Read the Tides",
        "Pirate's Cutlass",
        "Curious Obsession",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Pirates Island"
      ],
      "shortName": "PIRATES"
    },
    {
      "name": "PLUS ONE (1)",
      "cards": [
        "Armorcraft Judge",
        "Nessian Hornbeetle",
        "Ironshell Beetle",
        "Fertilid",
        "Wildwood Scourge",
        "Trufflesnout",
        "Pridemalkin",
        "Hunter's Edge",
        "Arbor Armament",
        "Invigorating Surge",
        "Primeval Bounty",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Plus One Forest"
      ],
      "shortName": "PLUS ONE"
    },
    {
      "name": "PLUS ONE (2)",
      "cards": [
        "Armorcraft Judge",
        "Nessian Hornbeetle",
        "Fertilid",
        "Ironshell Beetle",
        "Wildwood Scourge",
        "Trufflesnout",
        "Pridemalkin",
        "Hunter's Edge",
        "Arbor Armament",
        "Invigorating Surge",
        "Branching Evolution",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Plus One Forest"
      ],
      "shortName": "PLUS ONE"
    },
    {
      "name": "PLUS ONE (3)",
      "cards": [
        "Rishkar, Peema Renegade",
        "Nessian Hornbeetle",
        "Fertilid",
        "Scrounging Bandar",
        "Wildwood Scourge",
        "Trufflesnout",
        "Pridemalkin",
        "Hunter's Edge",
        "Inspiring Call",
        "Arbor Armament",
        "Invigorating Surge",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Plus One Forest"
      ],
      "shortName": "PLUS ONE"
    },
    {
      "name": "PLUS ONE (4)",
      "cards": [
        "Champion of Lambholt",
        "Nessian Hornbeetle",
        "Scrounging Bandar",
        "Wildwood Scourge",
        "Trufflesnout",
        "Pridemalkin",
        "Hunter's Edge",
        "Lifecrafter's Gift",
        "Arbor Armament",
        "Invigorating Surge",
        "Branching Evolution",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Plus One Forest"
      ],
      "shortName": "PLUS ONE"
    },
    {
      "name": "PREDATORY (1)",
      "cards": [
        "Somberwald Stag",
        "Sylvan Brushstrider",
        "Neyith of the Dire Hunt",
        "Brindle Shoat",
        "Dawntreader Elk",
        "Trufflesnout",
        "Sabertooth Mauler",
        "Irresistible Prey",
        "Time to Feed",
        "Crushing Canopy",
        "Fungal Rebirth",
        "Marauder's Axe",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Predatory Forest"
      ],
      "shortName": "PREDATORY"
    },
    {
      "name": "PREDATORY (2)",
      "cards": [
        "Gingerbrute",
        "Neyith of the Dire Hunt",
        "Affectionate Indrik",
        "Brindle Shoat",
        "Dawntreader Elk",
        "Trufflesnout",
        "Sabertooth Mauler",
        "Irresistible Prey",
        "Time to Feed",
        "Crushing Canopy",
        "Fungal Rebirth",
        "Marauder's Axe",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Predatory Forest"
      ],
      "shortName": "PREDATORY"
    },
    {
      "name": "PREDATORY (3)",
      "cards": [
        "Thragtusk",
        "Somberwald Stag",
        "Brindle Shoat",
        "Dawntreader Elk",
        "Gingerbrute",
        "Trufflesnout",
        "Sabertooth Mauler",
        "Irresistible Prey",
        "Time to Feed",
        "Crushing Canopy",
        "Fungal Rebirth",
        "Marauder's Axe",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Predatory Forest"
      ],
      "shortName": "PREDATORY"
    },
    {
      "name": "PREDATORY (4)",
      "cards": [
        "Ravenous Baloth",
        "Affectionate Indrik",
        "Brindle Shoat",
        "Dawntreader Elk",
        "Sylvan Brushstrider",
        "Trufflesnout",
        "Sabertooth Mauler",
        "Irresistible Prey",
        "Time to Feed",
        "Momentous Fall",
        "Crushing Canopy",
        "Fungal Rebirth",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Predatory Forest"
      ],
      "shortName": "PREDATORY"
    },
    {
      "name": "RAINBOW",
      "cards": [
        "Maelstrom Archangel",
        "Chamber Sentry",
        "Dinrova Horror",
        "Fusion Elemental",
        "Raging Regisaur",
        "Ironroot Warlord",
        "Alloy Myr",
        "Skittering Surveyor",
        "Prismite",
        "Auger Spree",
        "Prophetic Prism",
        "Lawmage's Binding",
        "Mirrodin's Core",
        "Rupture Spire",
        "Forest",
        "Island",
        "Mountain",
        "Plains",
        "Swamp",
        "Rainbow Terramorphic Expanse"
      ],
      "shortName": "RAINBOW"
    },
    {
      "name": "REANIMATED (1)",
      "cards": [
        "Mire Triton",
        "Cadaver Imp",
        "Crow of Dark Tidings",
        "Miasmic Mummy",
        "Tithebearer Giant",
        "Archfiend's Vessel",
        "Goremand",
        "Crypt Lurker",
        "Reanimate",
        "Funeral Rites",
        "Rise Again",
        "Eliminate",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Reanimated Swamp"
      ],
      "shortName": "REANIMATED"
    },
    {
      "name": "REANIMATED (2)",
      "cards": [
        "Mire Triton",
        "Crow of Dark Tidings",
        "Miasmic Mummy",
        "Carrion Grub",
        "Goremand",
        "Crypt Lurker",
        "Gloom Sower",
        "Reanimate",
        "Funeral Rites",
        "Macabre Waltz",
        "Rise Again",
        "Eliminate",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Reanimated Swamp"
      ],
      "shortName": "REANIMATED"
    },
    {
      "name": "REANIMATED (3)",
      "cards": [
        "Gravewaker",
        "Scourge of Nel Toth",
        "Mire Triton",
        "Crow of Dark Tidings",
        "Miasmic Mummy",
        "Goremand",
        "Crypt Lurker",
        "Exhume",
        "Funeral Rites",
        "Rise Again",
        "Eliminate",
        "Zombie Infestation",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Reanimated Swamp"
      ],
      "shortName": "REANIMATED"
    },
    {
      "name": "REANIMATED (4)",
      "cards": [
        "Mire Triton",
        "Crow of Dark Tidings",
        "Miasmic Mummy",
        "Carrion Grub",
        "Goremand",
        "Crypt Lurker",
        "Gloom Sower",
        "Rise of the Dark Realms",
        "Funeral Rites",
        "Soul Salvage",
        "Rise Again",
        "Eliminate",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Reanimated Swamp"
      ],
      "shortName": "REANIMATED"
    },
    {
      "name": "ROGUES (1)",
      "cards": [
        "Gonti, Lord of Luxury",
        "Mausoleum Turnkey",
        "Oona's Blackguard",
        "Lawless Broker",
        "Nightshade Stinger",
        "Nocturnal Feeder",
        "Thieves' Guild Enforcer",
        "Masked Blackguard",
        "Alchemist's Gift",
        "Finishing Blow",
        "Rogue's Gloves",
        "Stab Wound",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Rogues Swamp"
      ],
      "shortName": "ROGUES"
    },
    {
      "name": "ROGUES (2)",
      "cards": [
        "Corpse Traders",
        "Oona's Blackguard",
        "Corpse Hauler",
        "Lawless Broker",
        "Nightshade Stinger",
        "Nocturnal Feeder",
        "Thieves' Guild Enforcer",
        "Masked Blackguard",
        "Last Gasp",
        "Alchemist's Gift",
        "Rogue's Gloves",
        "Stab Wound",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Rogues Swamp"
      ],
      "shortName": "ROGUE"
    },
    {
      "name": "SEISMIC",
      "cards": [
        "Grim Lavamancer",
        "Cinder Elemental",
        "Seismic Elemental",
        "Ashmouth Hound",
        "Bloodrock Cyclops",
        "Molten Ravager",
        "Spitting Earth",
        "Magmaquake",
        "Magma Jet",
        "Volcanic Fallout",
        "Volcanic Geyser",
        "Mana Geode",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Seismic Mountain"
      ],
      "shortName": "SEISMIC"
    },
    {
      "name": "SMASHING (1)",
      "cards": [
        "Bloodrage Brawler",
        "Flametongue Kavu",
        "Borderland Marauder",
        "Heartfire Immolator",
        "Onakke Ogre",
        "Turret Ogre",
        "Bone Pit Brute",
        "Volcanic Salvo",
        "Fling",
        "Unleash Fury",
        "Shock",
        "Furious Rise",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Smashing Mountain"
      ],
      "shortName": "SMASHING"
    },
    {
      "name": "SMASHING (2)",
      "cards": [
        "Bloodrage Brawler",
        "Borderland Marauder",
        "Heartfire Immolator",
        "Onakke Ogre",
        "Turret Ogre",
        "Bone Pit Brute",
        "Volcanic Salvo",
        "Flames of the Raze-Boar",
        "Fling",
        "Hungry Flames",
        "Short Sword",
        "Furious Rise",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Smashing Mountain"
      ],
      "shortName": "SMASHING"
    },
    {
      "name": "SMASHING (3)",
      "cards": [
        "Hamletback Goliath",
        "Bloodrage Brawler",
        "Inferno Hellion",
        "Borderland Marauder",
        "Heartfire Immolator",
        "Onakke Ogre",
        "Turret Ogre",
        "Bone Pit Brute",
        "Fling",
        "Unleash Fury",
        "Sarkhan's Unsealing",
        "Furious Rise",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Smashing Mountain"
      ],
      "shortName": "SMASHING"
    },
    {
      "name": "SMASHING (4)",
      "cards": [
        "Etali, Primal Storm",
        "Bloodrage Brawler",
        "Bloodshot Trainee",
        "Borderland Marauder",
        "Heartfire Immolator",
        "Onakke Ogre",
        "Turret Ogre",
        "Bone Pit Brute",
        "Fling",
        "Hungry Flames",
        "Furious Rise",
        "Furor of the Bitten",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Smashing Mountain"
      ],
      "shortName": "SMASHING"
    },
    {
      "name": "SPELLCASTING (1)",
      "cards": [
        "Thermo-Alchemist",
        "Living Lightning",
        "Lightning Visionary",
        "Chandra's Pyreling",
        "Kinetic Augur",
        "Heartfire Immolator",
        "Blindblast",
        "Hungry Flames",
        "Goblin Wizardry",
        "Shock",
        "Thrill of Possibility",
        "Double Vision",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Spellcasting Mountain"
      ],
      "shortName": "SPELLCASTING"
    },
    {
      "name": "SPELLCASTING (2)",
      "cards": [
        "Young Pyromancer",
        "Kiln Fiend",
        "Lightning Visionary",
        "Thermo-Alchemist",
        "Chandra's Pyreling",
        "Kinetic Augur",
        "Heartfire Immolator",
        "Flame Lash",
        "Hungry Flames",
        "Shock",
        "Thrill of Possibility",
        "Double Vision",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Spellcasting Mountain"
      ],
      "shortName": "SPELLCASTING"
    },
    {
      "name": "SPELLCASTING (3)",
      "cards": [
        "Charmbreaker Devils",
        "Dualcaster Mage",
        "Living Lightning",
        "Lightning Visionary",
        "Thermo-Alchemist",
        "Chandra's Pyreling",
        "Kinetic Augur",
        "Heartfire Immolator",
        "Dragon Fodder",
        "Hungry Flames",
        "Shock",
        "Thrill of Possibility",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Spellcasting Mountain"
      ],
      "shortName": "SPELLCASTING"
    },
    {
      "name": "SPELLCASTING (4)",
      "cards": [
        "Kiln Fiend",
        "Lightning Visionary",
        "Thermo-Alchemist",
        "Chandra's Pyreling",
        "Kinetic Augur",
        "Heartfire Immolator",
        "Doublecast",
        "Immolating Gyre",
        "Crash Through",
        "Hungry Flames",
        "Shock",
        "Thrill of Possibility",
        "Thriving Bluff",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Mountain",
        "Spellcasting Mountain"
      ],
      "shortName": "SPELLCASTING"
    },
    {
      "name": "SPIRITS (1)",
      "cards": [
        "Battleground Geist",
        "Departed Deckhand",
        "Nebelgast Herald",
        "Murmuring Phantasm",
        "Shacklegeist",
        "Roaming Ghostlight",
        "Tome Anima",
        "Winged Words",
        "Essence Flux",
        "Befuddle",
        "Frost Breath",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Spirits Island"
      ],
      "shortName": "SPIRITS"
    },
    {
      "name": "SPIRITS (2)",
      "cards": [
        "Rattlechains",
        "Battleground Geist",
        "Departed Deckhand",
        "Nebelgast Herald",
        "Shacklegeist",
        "Roaming Ghostlight",
        "Tome Anima",
        "Winged Words",
        "Rewind",
        "Rookie Mistake",
        "Frost Breath",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Spirits Island"
      ],
      "shortName": "SPIRITS"
    },
    {
      "name": "SPOOKY (1)",
      "cards": [
        "Bone Picker",
        "Eternal Taskmaster",
        "Gristle Grinner",
        "Dutiful Attendant",
        "Liliana's Standard Bearer",
        "Crypt Lurker",
        "Caged Zombie",
        "Fetid Imp",
        "Barter in Blood",
        "Finishing Blow",
        "Village Rites",
        "Malefic Scythe",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Spooky Swamp"
      ],
      "shortName": "SPOOKY"
    },
    {
      "name": "SPOOKY (2)",
      "cards": [
        "Harvester of Souls",
        "Bone Picker",
        "Eternal Taskmaster",
        "Gristle Grinner",
        "Dutiful Attendant",
        "Sanitarium Skeleton",
        "Crypt Lurker",
        "Caged Zombie",
        "Barter in Blood",
        "Bone Splinters",
        "Finishing Blow",
        "Malefic Scythe",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Spooky Swamp"
      ],
      "shortName": "SPOOKY"
    },
    {
      "name": "SPOOKY (3)",
      "cards": [
        "Ogre Slumlord",
        "Bone Picker",
        "Eternal Taskmaster",
        "Gristle Grinner",
        "Dutiful Attendant",
        "Liliana's Devotee",
        "Crypt Lurker",
        "Caged Zombie",
        "Fetid Imp",
        "Languish",
        "Finishing Blow",
        "Malefic Scythe",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Spooky Swamp"
      ],
      "shortName": "SPOOKY"
    },
    {
      "name": "SPOOKY (4)",
      "cards": [
        "Bone Picker",
        "Eternal Taskmaster",
        "Gristle Grinner",
        "Dutiful Attendant",
        "Plagued Rusalka",
        "Sanitarium Skeleton",
        "Liliana's Devotee",
        "Crypt Lurker",
        "Caged Zombie",
        "Finishing Blow",
        "Malefic Scythe",
        "Black Market",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Spooky Swamp"
      ],
      "shortName": "SPOOKY"
    },
    {
      "name": "TEFERI",
      "cards": [
        "Teferi, Master of Time",
        "Prescient Chimera",
        "Sage's Row Savant",
        "Tolarian Kraken",
        "Vodalian Arcanist",
        "Teferi's Protege",
        "Talrand's Invocation",
        "Exclude",
        "Leave in the Dust",
        "Opt",
        "Teferi's Ageless Insight",
        "Teferi's Tutelage",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island"
      ],
      "shortName": "TEFERI"
    },
    {
      "name": "TREE-HUGGING (1)",
      "cards": [
        "Primordial Sage",
        "Wall of Blossoms",
        "Ambassador Oak",
        "Burlfist Oak",
        "Warden of the Woods",
        "Llanowar Visionary",
        "Snarespinner",
        "Gnarled Sage",
        "Nature's Way",
        "Explore",
        "Aggressive Urge",
        "Crushing Canopy",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Tree-Hugging Forest"
      ],
      "shortName": "TREE-HUGGING"
    },
    {
      "name": "TREE-HUGGING (2)",
      "cards": [
        "Primordial Sage",
        "Wall of Blossoms",
        "Ambassador Oak",
        "Burlfist Oak",
        "Warden of the Woods",
        "Llanowar Visionary",
        "Snarespinner",
        "Gnarled Sage",
        "Nature's Way",
        "Explore",
        "Crushing Canopy",
        "Wildsize",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Tree-Hugging Forest"
      ],
      "shortName": "TREE-HUGGING"
    },
    {
      "name": "TREE-HUGGING (3)",
      "cards": [
        "Wall of Blossoms",
        "Ambassador Oak",
        "Jolrael, Mwonvuli Recluse",
        "Burlfist Oak",
        "Warden of the Woods",
        "Llanowar Visionary",
        "Snarespinner",
        "Gnarled Sage",
        "Nature's Way",
        "Explore",
        "Aggressive Urge",
        "Crushing Canopy",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Tree-Hugging Forest"
      ],
      "shortName": "TREE-HUGGING"
    },
    {
      "name": "TREE-HUGGING (4)",
      "cards": [
        "Soul of the Harvest",
        "Wall of Blossoms",
        "Burlfist Oak",
        "Warden of the Woods",
        "Llanowar Visionary",
        "Snarespinner",
        "Gnarled Sage",
        "Nature's Way",
        "Explore",
        "Crushing Canopy",
        "Wildsize",
        "Verdant Embrace",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Tree-Hugging Forest"
      ],
      "shortName": "TREE-HUGGING"
    },
    {
      "name": "UNDER THE SEA (1)",
      "cards": [
        "Sigiled Starfish",
        "Octoprophet",
        "Wishful Merfolk",
        "Aegis Turtle",
        "Pursued Whale",
        "Tolarian Kraken",
        "Waker of Waves",
        "Voyage's End",
        "Unstable Obelisk",
        "Waterknot",
        "Rousing Read",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Under the Sea Island"
      ],
      "shortName": "UNDER THE SEA"
    },
    {
      "name": "UNDER THE SEA (2)",
      "cards": [
        "Cryptic Serpent",
        "Sigiled Starfish",
        "Octoprophet",
        "Wishful Merfolk",
        "Aegis Turtle",
        "Pursued Whale",
        "Waker of Waves",
        "Whelming Wave",
        "Sweep Away",
        "Unstable Obelisk",
        "Waterknot",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Under the Sea Island"
      ],
      "shortName": "UNDER THE SEA"
    },
    {
      "name": "UNICORNS",
      "cards": [
        "Inspiring Unicorn",
        "Emiel the Blessed",
        "Brightmare",
        "Mesa Unicorn",
        "Ronom Unicorn",
        "Valorous Steed",
        "Daybreak Charger",
        "Valorous Stance",
        "Cloudshift",
        "Inspired Charge",
        "Blessed Sanctuary",
        "Faith's Fetters",
        "Thriving Heath",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Unicorns Plains"
      ],
      "shortName": "UNICORNS"
    },
    {
      "name": "VAMPIRES (1)",
      "cards": [
        "Blood Artist",
        "Bloodbond Vampire",
        "Gifted Aetherborn",
        "Kalastria Nightwatch",
        "Nocturnal Feeder",
        "Vito, Thorn of the Dusk Rose",
        "Silversmote Ghoul",
        "Gloom Sower",
        "Agonizing Syphon",
        "Sanguine Indulgence",
        "Last Gasp",
        "Eternal Thirst",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Vampires Swamp"
      ],
      "shortName": "VAMPIRES"
    },
    {
      "name": "VAMPIRES (2)",
      "cards": [
        "Blood Host",
        "Bloodbond Vampire",
        "Gifted Aetherborn",
        "Child of Night",
        "Nocturnal Feeder",
        "Vito, Thorn of the Dusk Rose",
        "Silversmote Ghoul",
        "Gloom Sower",
        "Agonizing Syphon",
        "Sanguine Indulgence",
        "Last Gasp",
        "Eternal Thirst",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Vampires Swamp"
      ],
      "shortName": "VAMPIRES"
    },
    {
      "name": "VAMPIRES (3)",
      "cards": [
        "Sangromancer",
        "Bloodbond Vampire",
        "Gifted Aetherborn",
        "Sengir Vampire",
        "Nocturnal Feeder",
        "Vampire Neonate",
        "Silversmote Ghoul",
        "Gloom Sower",
        "Agonizing Syphon",
        "Sanguine Indulgence",
        "Last Gasp",
        "Exquisite Blood",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Vampires Swamp"
      ],
      "shortName": "VAMPIRES"
    },
    {
      "name": "VAMPIRES (4)",
      "cards": [
        "Drana, Liberator of Malakir",
        "Bloodbond Vampire",
        "Falkenrath Noble",
        "Gifted Aetherborn",
        "Child of Night",
        "Nocturnal Feeder",
        "Silversmote Ghoul",
        "Gloom Sower",
        "Agonizing Syphon",
        "Sanguine Indulgence",
        "Last Gasp",
        "Mark of the Vampire",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Vampires Swamp"
      ],
      "shortName": "VAMPIRES"
    },
    {
      "name": "WALLS",
      "cards": [
        "Wall of Blossoms",
        "Towering Titan",
        "Carven Caryatid",
        "Gargoyle Sentinel",
        "Overgrown Battlement",
        "Grave Bramble",
        "Wall of Vines",
        "Roving Keep",
        "Portcullis Vine",
        "Crushing Canopy",
        "Warmonger's Chariot",
        "Assault Formation",
        "Thriving Grove",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Forest",
        "Walls Forest"
      ],
      "shortName": "WALLS"
    },
    {
      "name": "WELL-READ (1)",
      "cards": [
        "Suspicious Bookcase",
        "Ormos, Archive Keeper",
        "Oneirophage",
        "Erratic Visionary",
        "Runed Servitor",
        "Tolarian Kraken",
        "Tome Anima",
        "Library Larcenist",
        "Opt",
        "Curiosity",
        "Narcolepsy",
        "Rousing Read",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Well-Read Island"
      ],
      "shortName": "WELL-READ"
    },
    {
      "name": "WELL-READ (2)",
      "cards": [
        "Ormos, Archive Keeper",
        "Oneirophage",
        "Erratic Visionary",
        "Runed Servitor",
        "Tolarian Kraken",
        "Tome Anima",
        "Library Larcenist",
        "Opt",
        "Arcane Encyclopedia",
        "Curiosity",
        "Capture Sphere",
        "Rousing Read",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Well-Read Island"
      ],
      "shortName": "WELL-READ"
    },
    {
      "name": "WELL-READ (3)",
      "cards": [
        "Oneirophage",
        "Suspicious Bookcase",
        "Cloudreader Sphinx",
        "Erratic Visionary",
        "Runed Servitor",
        "Tolarian Kraken",
        "Tome Anima",
        "Library Larcenist",
        "Opt",
        "Rhystic Study",
        "Curiosity",
        "Narcolepsy",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Well-Read Island"
      ],
      "shortName": "WELL-READ"
    },
    {
      "name": "WELL-READ (4)",
      "cards": [
        "Mystic Archaeologist",
        "Oneirophage",
        "Suspicious Bookcase",
        "Cloudreader Sphinx",
        "Runed Servitor",
        "Tolarian Kraken",
        "Tome Anima",
        "Library Larcenist",
        "Read the Runes",
        "Opt",
        "Curiosity",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Well-Read Island"
      ],
      "shortName": "WELL-READ"
    },
    {
      "name": "WITCHCRAFT (1)",
      "cards": [
        "Bogbrew Witch",
        "Witch of the Moors",
        "Malakir Familiar",
        "Tempting Witch",
        "Bloodhunter Bat",
        "Cauldron Familiar",
        "Festering Newt",
        "Festering Newt",
        "Bake into a Pie",
        "Finishing Blow",
        "Bubbling Cauldron",
        "Witch's Cauldron",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Witchcraft Swamp"
      ],
      "shortName": "WITCHCRAFT"
    },
    {
      "name": "WITCHCRAFT (2)",
      "cards": [
        "Tempting Witch",
        "Bogbrew Witch",
        "Witch of the Moors",
        "Swarm of Bloodflies",
        "Black Cat",
        "Bloodhunter Bat",
        "Festering Newt",
        "Festering Newt",
        "Blood Divination",
        "Bake into a Pie",
        "Last Gasp",
        "Bubbling Cauldron",
        "Thriving Moor",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Swamp",
        "Witchcraft Swamp"
      ],
      "shortName": "WITCHCRAFT"
    },
    {
      "name": "WIZARDS (1)",
      "cards": [
        "Talrand, Sky Summoner",
        "Exclusion Mage",
        "Sage's Row Savant",
        "Shipwreck Dowser",
        "Vodalian Arcanist",
        "Talrand's Invocation",
        "Winged Words",
        "Read the Tides",
        "Wizard's Retort",
        "Befuddle",
        "Frost Breath",
        "Opt",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Wizards Island"
      ],
      "shortName": "WIZARDS"
    },
    {
      "name": "WIZARDS (2)",
      "cards": [
        "Exclusion Mage",
        "Crookclaw Transmuter",
        "Sage's Row Savant",
        "Sea Gate Oracle",
        "Shipwreck Dowser",
        "Vodalian Arcanist",
        "Talrand's Invocation",
        "Winged Words",
        "Read the Tides",
        "Wizard's Retort",
        "Rookie Mistake",
        "Opt",
        "Riptide Laboratory",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Wizards Island"
      ],
      "shortName": "WIZARDS"
    },
    {
      "name": "WIZARDS (3)",
      "cards": [
        "Talrand, Sky Summoner",
        "Sage's Row Savant",
        "Shipwreck Dowser",
        "Vodalian Arcanist",
        "Teferi's Protege",
        "Talrand's Invocation",
        "Winged Words",
        "Read the Tides",
        "Wizard's Retort",
        "Unsubstantiate",
        "Opt",
        "Capture Sphere",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Wizards Island"
      ],
      "shortName": "WIZARDS"
    },
    {
      "name": "WIZARDS (4)",
      "cards": [
        "Sage's Row Savant",
        "Storm Sculptor",
        "Barrin, Tolarian Archmage",
        "Shipwreck Dowser",
        "Vodalian Arcanist",
        "Teferi's Protege",
        "Talrand's Invocation",
        "Read the Tides",
        "Wizard's Retort",
        "Peel from Reality",
        "Rain of Revelation",
        "Frost Breath",
        "Thriving Isle",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Island",
        "Wizards Island"
      ],
      "shortName": "WIZARDS"
    }
  ]
};

export default data;
